name: CI

on: [push]

jobs:
  run:
    name: Test on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [10, 12, 14, 16, 18]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: |
          npm install
        env:
          CI: true
      - name: lint
        run: |
          npm run lint
      - name: test
        run: npm test
        env:
          CI: true
      - name: build
        run: npm run build
